name: ci

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:    
      - uses: actions/checkout@v3
        with:
            ref: V23.02.0-trunk.0256
      - name: download vidwo
        id: download
        shell: bash
        run: |
          ls ./patch/misc/
          ./compile.sh \
          BOARD=eaidk-610 \
          BRANCH=current \
          RELEASE=bullseye KERNEL_ONLY=no \
          KERNEL_CONFIGURE=no USE_MAINLINE_GOOGLE_MIRROR=yes BUILD_DESKTOP=yes  \
          DESKTOP_ENVIRONMENT="xfce" RELEASE="focal" DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base DESKTOP_APPGROUPS_SELECTED="browsers 3dsupport"  COMPRESS_OUTPUTIMAGE=yes  
          

          ls output/images/

          
          
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: img
          path: output/images/*
      

      - name: Release
        uses: softprops/action-gh-release@v1
        continue-on-error: false
        with:
          name: ${{ steps.download.outputs.release_name }}
          tag_name: ${{ github.run_id }}
          #body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            output/images/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
